{{- range .Values.chartDiscovery.instances }}
{{- $name := default (printf "platz-chart-discovery-%s" .name) .serviceAccount.name }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
  {{- with .serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
