{{- if .Values.backupJob.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backupJob.serviceAccount.name }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.backupJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
