apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-chart-discovery
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      platzService: chart-discovery
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        platzService: chart-discovery
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.chartDiscovery.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: chart-discovery
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.chartDiscovery.image.repository }}:{{ .Values.chartDiscovery.image.tag }}"
          imagePullPolicy: {{ .Values.chartDiscovery.image.pullPolicy }}
          command:
            - /root/platz-chart-discovery
            - --debug
            - --all-debug
          env:
            - name: DATABASE_URL
              value: '{{ include "chart.databaseUrl" . }}'
            - name: PLATZ_OWN_URL
              value: '{{ include "platz.ownUrl" . }}'
            - name: PLATZ_ECR_EVENTS_QUEUE
              value: '{{ .Values.chartDiscovery.ecr.queueName }}'
            - name: PLATZ_ECR_EVENTS_REGION
              value: '{{ .Values.chartDiscovery.ecr.regionName }}'
            - name: RUST_BACKTRACE
              value: '1'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
