apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-task-runner
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
      platzService: task-runner
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
        platzService: task-runner
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.taskRunner.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: task-runner
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: '{{- .Values.taskRunner.image.repository }}:{{ .Values.taskRunner.image.tag }}'
          imagePullPolicy: {{ .Values.taskRunner.image.pullPolicy }}
          command:
            - /root/platz-task-runner
            - --debug
            - --all-debug
          env:
            - name: DATABASE_URL
              value: '{{ include "chart.databaseUrl" . }}'
            - name: PLATZ_OWN_URL
              value: '{{ include "platz.ownUrl" . }}'
            - name: PLATZ_HELM_IMAGE
              value: '{{- .Values.taskRunner.helmImage.repository }}:{{ .Values.taskRunner.helmImage.tag }}'
            - name: PLATZ_SELF_NAMESPACE
              value: '{{ .Release.Namespace }}'
            - name: PLATZ_SELF_SERVICE_ACCOUNT_NAME
              value: {{ .Values.taskRunner.serviceAccount.name }}
            - name: RUST_BACKTRACE
              value: '1'
          resources:
            {{- toYaml .Values.taskRunner.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
