apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    platzService: api
