apiVersion: v2
appVersion: "0.3.0-beta.4"
description: A Helm chart for Platz.io
name: platzio
type: application
version: "0.3.0-beta.4"
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.21
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: added
      description: Remove `-chart` and `-charts` suffixes from Helm repositories when converting their names to a deployment kind
