apiVersion: v2
appVersion: "0.4.6"
version: "0.4.6"
description: A Helm chart for Platz.io
name: platzio
type: application
keywords:
  - helm
  - chart
  - cd
  - continuous deployment
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.7.1
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: added
      description: /api/v2/helm-charts can now filter charts in use or potential upgrades using ?in_use=true
    - kind: changed
      description: Helm registry kinds is now saved in the database instead of being deduced in the frontend
    - kind: added
      description: /api/v2/helm-registries allows filtering registries by kind
    - kind: added
      description: The platz section in injected values now contains the entire cluster as returned from the API
    - kind: fixed
      description: The frontend performs the initial load much faster by only loading charts in use
    - kind: changed
      description: The frontend shows loading progress when it has to load all charts of a specific kind/registry
    - kind: changed
      description: Postgresql subchart updated to 11.7.1
