apiVersion: v2
appVersion: "0.5.3-beta.1"
version: "0.5.3-beta.1"
description: A Helm chart for Platz.io
name: platzio
type: application
keywords:
  - helm
  - chart
  - cd
  - continuous deployment
icon: https://raw.githubusercontent.com/platzio/frontend/main/src/assets/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.13
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: fixed
      description: Fixed pagination showing wrong page numbers or ellipsis
    - kind: fixed
      description: /api/v2/k8s-clusters/{id} always returning NOT FOUND
    - kind: fixed
      description: Deployment page overview now has a border
    - kind: fixed
      description: Clicking logs uses offcanvas instead of expanding inline
    - kind: fixed
      description: Increased k8s-agent memory limit to 1Gi
