apiVersion: v2
appVersion: "0.3.0-beta.5"
description: A Helm chart for Platz.io
name: platzio
type: application
version: "0.3.0-beta.5"
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.22
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: added
      description: Cluster TLS secret name configuration.
    - kind: added
      description: The "platz:" section injected into values now contains "env_id" and "env_name" properties.
    - kind: added
      description: Ingress hostnames format. A new v1beta2 features API version contains an "ingress" block replacing the previous "standard_ingress" flag. The new ingress block allows for selecting whether an ingress hostname is built from the deployment kind and name (the behavior so far) or just the deployment name.
    - kind: changed
      description: The task-runner worker has been renamed to k8s-agent.
    - kind: changed
      description: The chart now supports multiple k8s-agents using a top-level "k8sAgents" block that contains a list of "name" and "serviceAccount" definitions for each k8s-agent.
    - kind: changed
      description: k8s-agent deployment changed to a statefulset.
    - kind: changed
      description: Upgraded postgresql subchart to 11.1.22.
