apiVersion: v2
appVersion: "0.3.0-beta.0"
description: A Helm chart for Platz.io
name: platzio
type: application
version: "0.3.0-beta.0"
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.21
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: fixed
      description: Grafana configuration fixes (thanks @vmalloc!)
    - kind: changed
      description: PostgreSQL chart upgraded from 11.1.6 to 11.1.21
    - kind: added
      description: Helm was upgraded to 3.8.2
