apiVersion: v2
appVersion: "0.3.0-beta.7"
description: A Helm chart for Platz.io
name: platzio
type: application
version: "0.3.0-beta.7"
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.22
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: fixed
      description: Fixed update secret API not updating the updated_at property
    - kind: fixed
      description: Fixed env names to be case-insensitive unique
    - kind: added
      description: New env secrets screen with collection creation, secret renaming, editing and deletion
