apiVersion: v2
appVersion: "0.2.2"
description: A Helm chart for Platz.io
name: platzio
type: application
version: "0.2.2"
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.5
    condition: postgresql.enabled

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Added Grafana URL and data-source name to clusters. This adds an "Open Logs" link that opens Grafana with the deployment logs.
