apiVersion: v2
appVersion: "0.3.4"
version: "0.3.4"
description: A Helm chart for Platz.io
name: platzio
type: application
keywords:
  - helm
  - chart
  - cd
  - continuous deployment
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.29
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: fixed
      description: Fixed Deployment kinds list to remove duplicates
