apiVersion: v2
appVersion: "0.4.7"
version: "0.4.7"
description: A Helm chart for Platz.io
name: platzio
type: application
keywords:
  - helm
  - chart
  - cd
  - continuous deployment
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.8
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: added
      description: New logo and mascot by @vmalloc!
    - kind: added
      description: Deployment icons defined through Helm chart
    - kind: added
      description: Support for ingress classes
    - kind: fixed
      description: Custom resources with no lifecycle hooks are automatically marked as ready
    - kind: changed
      description: chart-ext was moved from the backend to a separate crate
    - kind: fixed
      description: A global admin can see and automatically be an admin of all envs
    - kind: fixed
      description: Display deployment resource status in resource page
