apiVersion: v2
appVersion: "0.5.0-beta.8"
version: "0.5.0-beta.8"
description: A Helm chart for Platz.io
name: platzio
type: application
keywords:
  - helm
  - chart
  - cd
  - continuous deployment
icon: https://raw.githubusercontent.com/platzio/frontend/main/src/assets/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.13
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: Upgraded to diesel-2.0
    - kind: added
      description: Chart.yaml is now parsed for version and git metadata
    - kind: added
      description: Chart playground for testing chart extensions
    - kind: added
      description: Allow running multiple chart-discovery workers
    - kind: changed
      description: Tag parsing has to be explicitly enabled in one chart-discovery instance
    - kind: added
      description: OpenAPI schemas are now generated on backend build and saved for each release
    - kind: changed
      description: New Kubernetes clusters are now ignored by default and have to be enabled manually (thanks @ayalash!)
    - kind: fixed
      description: Fixed metrics for task statuses missing zero values (thanks @vmalloc!)
    - kind: changed
      description: The frontend now uses an SDK generated from an OpenAPI schema
    - kind: added
      description: Dark mode 🌚🎉 (thanks Bootstrap!)
