apiVersion: v2
appVersion: "0.3.0-beta.8"
description: A Helm chart for Platz.io
name: platzio
type: application
version: "0.3.0-beta.8"
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.23
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: Upgraded postgresql subchart to 11.1.23
    - kind: added
      description: API access tokens can now identify deployments in addition to users
    - kind: added
      description: Added configuration for automatically adding new users to envs
