apiVersion: v2
appVersion: "0.4.0"
version: "0.4.0"
description: A Helm chart for Platz.io
name: platzio
type: application
keywords:
  - helm
  - chart
  - cd
  - continuous deployment
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.5.0
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: added
      description: Helm tag format parsing
    - kind: changed
      description: Postgresql subchart updated to 11.5.0
