apiVersion: v2
appVersion: "0.3.2"
version: "0.3.2"
description: A Helm chart for Platz.io
name: platzio
type: application
keywords:
  - helm
  - chart
  - cd
  - continuous deployment
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.25
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: added
      description: A secret with deployment access token is now refreshed every 30 minutes for every deployment
    - kind: changed
      description: Upgraded postgresql subchart to 11.1.25
