apiVersion: v2
appVersion: "0.4.3-beta.1"
version: "0.4.3-beta.1"
description: A Helm chart for Platz.io
name: platzio
type: application
keywords:
  - helm
  - chart
  - cd
  - continuous deployment
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.6.10
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "true"
  artifacthub.io/changes: |
    - kind: changed
      description: ingress.hosts renamed to ingress.rules
    - kind: changed
      description: host is ingress.rules is optional
    - kind: changed
      description: Use PLATZ_OWN_URL for generating OIDC callback
    - kind: added
      description: Added optional ownUrlOverride value
    - kind: fixed
      description: Fixed --admin_email option to --admin-email in backend
    - kind: fixed
      description: Reduced backend image size from ~2GB to ~500MB
    - kind: changed
      description: Postgresql subchart updated to 11.6.10
