apiVersion: v2
appVersion: "0.5.2"
version: "0.5.2"
description: A Helm chart for Platz.io
name: platzio
type: application
keywords:
  - helm
  - chart
  - cd
  - continuous deployment
icon: https://raw.githubusercontent.com/platzio/frontend/main/src/assets/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.13
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: added
      description: Added env_id filter for /api/v2/deployments (thanks @ayalash!)
    - kind: added
      description: Users can now be deactivated (thanks @ayalash!)
    - kind: added
      description: Env deletion (thanks @ayalash!)
    - kind: added
      description: New showIf options for UI schema inputs (thanks @pyros82!)
    - kind: added
      description: Pagination for Helm registry page and deployment task history
