apiVersion: v2
appVersion: "0.4.8"
version: "0.4.8"
description: A Helm chart for Platz.io
name: platzio
type: application
keywords:
  - helm
  - chart
  - cd
  - continuous deployment
icon: https://raw.githubusercontent.com/platzio/frontend/main/public/Logo.svg
sources:
  - https://github.com/platzio

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.9.8
    condition: postgresql.enabled

annotations:
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: fixed
      description: Fix task failure/success output manipulation (thanks @vmalloc!)
    - kind: fixed
      description: Avoid refreshing credentials of disabled deployments
    - kind: fixed
      description: k8s-agent will not exit on task failure anymore
    - kind: added
      description: Release builds now have debug info and show full backtraces (thanks @vmalloc!)
    - kind: fixed
      description: Fixed some charts missing when using ?in_use=true in API (thanks @vmalloc!)
    - kind: added
      description: Added context to errors around Helm chart pulling
    - kind: fixed
      description: Handle disconnections from control plane when running task pods (thanks @vmalloc!)
    - kind: fixed
      description: Fixed chart-discovery getting OOMKilled when scrubbing existing tags on startup
    - kind: fixed
      description: Fixed frontend crash when a chart had no features
    - kind: fixed
      description: Fixed to show registry icons when no icon is defined in chart features
    - kind: fixed
      description: Fix undefined error in findCollectionDependencies (thanks @vmalloc!)
    - kind: fixed
      description: Added log for missing charts in findCollectionDependencies (thanks @vmalloc!)
